### ISSUE TITLE
هناك مشاكل مع إضاءة السماء.

### ISSUE THREAD

**Issue by WOLFxxxxxx** [luis605/Lit-Engine-OLD#43]
![a1](https://github.com/user-attachments/assets/607d74b2-b9b3-4b68-a3a6-4635b7a51adf)

![a2](https://github.com/user-attachments/assets/b8ece0d3-61a2-43c9-a451-a33a9ef4900e)

**Comment by luis605** [comment]
What's the issue?

**Comment by WOLFxxxxxx** [comment]
Sky lighting does not show images on the object

Only sunlight exposes images to the object.

![a1](https://github.com/user-attachments/assets/f0b752be-40f3-485f-baba-a016f22fc7f3)
![a2](https://github.com/user-attachments/assets/0aaf4c22-5e5a-4c03-99ec-e55ab553c2b2)

**Comment by luis605** [comment]
The lighting shader handles the textures. What's happening is that the diffuse texture is calculated based on the light objects, not the ambient light. There are 2 known issues that happened after the shader rewrite which is that and black dots if the light is near the origin. They are relatively easy to fix, but since I don't have much time to work on the engine they haven't been fixed yet.

**Comment by luis605** [comment]
I have uploaded a fix to github. Closing the issue as fixed.
